uploads = []
generated = []

[[outputs]]
id = "qpWu_cX2397hUXEET-qTp"
uri = "file://mycode.tar.gz"
type = "unspecified"
title = "mycode.tar.gz — RIA BOT source code"

[[outputs]]
id = "IfmqxftdDwrazMS_bNY3v"
uri = "file://ria-bot-code.tar.gz"
type = "unspecified"
title = "ria-bot-code.tar.gz"

[[outputs]]
id = "45WrzrO820G2pp_t0l3Ms"
uri = "file://ria-bot-latest.tar.gz"
type = "unspecified"
title = "ria-bot-latest.tar.gz"

[[outputs]]
id = "gmdNdt5MYblSRI8l8PxA-"
uri = "file://ria-bot-codebase.tar.gz"
type = "unspecified"
title = "RIA Bot — Full Codebase (.tar.gz)"

[[outputs]]
id = "-CfMpePDZFmQzNrfp2jWZ"
uri = "file://ria-bot-current.tar.gz"
type = "unspecified"
title = "ria-bot-current.tar.gz"
